<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.45" />
    <xacro:property name="base_width" value="0.30" />
    <xacro:property name="base_height" value="0.10"/>
    <xacro:property name="wheel_radius" value="0.06" />
    <xacro:property name="wheel_length" value="0.03"/>
    <xacro:property name="mast_radius" value="0.015" />
    <xacro:property name="mast_length" value="0.25" />
    <xacro:property name="camera_length" value="0.05"/>
    <xacro:property name="camera_width" value="0.05"/>
    <xacro:property name="camera_height" value="0.04"/>

    <link name="base_footprint" />


    <link name="base_link">
        <visual>
            <geometry>
                <box size="0.45 0.30 0.10"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="dark_gray" />
        </visual>
        <collision>
            <geometry>
                <box size="0.45 0.30 0.10"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" 
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="black"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0" o_rpy="0 0 0"/>
        </link>
    </xacro:macro>


    <xacro:wheel prefix="left_back" />
    <xacro:wheel prefix="left_front" />
    <xacro:wheel prefix="right_back" />
    <xacro:wheel prefix="right_front" />
    
    <link name="upper_base_link">
        <visual>
            <geometry>
                <box size="0.35 0.20 0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="light_gray" />
        </visual>
        <collision>
            <geometry>
                <box size="0.35 0.20 0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="1.0" x="0.35" y="0.20" z="0.05" 
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <!-- <link name="mast_link">
        <visual>
            <geometry>
                <cylinder radius="${mast_radius}" length="${mast_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="metallic_gray" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${mast_radius}" length="${mast_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.8" r="${mast_radius}" l="${mast_length}" 
                                    o_xyz="0 0 0" o_rpy="0 0 0" />
    </link> -->

    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>



    <joint name="base_left_back_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_back_wheel"/>
        <origin xyz="-0.125 -0.15 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_front_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel"/>
        <origin xyz="0.125 -0.15 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_back_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_back_wheel"/>
        <origin xyz="-0.125 0.15 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_front_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_front_wheel"/>
        <origin xyz="0.125 0.15 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="upper_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="upper_base_link"/>
        <origin xyz="0 0 0.05" rpy="0 0 0" />
        
    </joint>

    <!-- <joint name="mast_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="mast_link"/>
        <origin xyz="0 0 0.175" rpy="0 0 0" />
    </joint> -->

    

      <!-- ================= Wheel friction tuning ================= -->

    <gazebo reference="left_front_wheel">
        <collision>
            <surface>
                <friction>
                    <ode>
                        <mu>1.0</mu>      <!-- forward -->
                        <mu2>0.2</mu2>    <!-- sideways -->
                        <slip1>0.0</slip1>
                        <slip2>0.1</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
    </gazebo>

    <gazebo reference="right_front_wheel">
        <collision>
            <surface>
                <friction>
                    <ode>
                        <mu>1.0</mu>      <!-- forward -->
                        <mu2>0.2</mu2>    <!-- sideways -->
                        <slip1>0.0</slip1>
                        <slip2>0.1</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
    </gazebo>

    <gazebo reference="left_back_wheel">
        <collision>
            <surface>
                <friction>
                    <ode>
                        <mu>1.0</mu>      <!-- forward -->
                        <mu2>0.2</mu2>    <!-- sideways -->
                        <slip1>0.0</slip1>
                        <slip2>0.1</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
    </gazebo>

    <gazebo reference="right_back_wheel">
        <collision>
            <surface>
                <friction>
                    <ode>
                        <mu>1.0</mu>      <!-- forward -->
                        <mu2>0.2</mu2>    <!-- sideways -->
                        <slip1>0.0</slip1>
                        <slip2>0.1</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
    </gazebo>






</robot>